"""
Skills Taxonomy — variant → canonical name mapping.

Fix 5 from atsfix.md: massively expanded to cover SSR, common abbreviations,
two-word phrases, and all variants needed for the Scandid JD test case.
"""

# ── Alias → Canonical skill mapping ──────────────────────────────────────────
# Applied before keyword extraction and TF-IDF so scoring uses canonical names.
SKILL_ALIASES: dict[str, str] = {

    # ── JavaScript / Frontend ─────────────────────────────────────────────────
    "react":                    "React",
    "reactjs":                  "React",
    "react.js":                 "React",
    "react js":                 "React",
    "nextjs":                   "Next.js",
    "next.js":                  "Next.js",
    "next js":                  "Next.js",
    "vuejs":                    "Vue.js",
    "vue.js":                   "Vue.js",
    "vue js":                   "Vue.js",
    "angular":                  "Angular",
    "angularjs":                "Angular",
    "svelte":                   "Svelte",
    "javascript":               "JavaScript",
    "js":                       "JavaScript",
    "typescript":               "TypeScript",
    "ts":                       "TypeScript",
    "nodejs":                   "Node.js",
    "node.js":                  "Node.js",
    "node js":                  "Node.js",
    "node":                     "Node.js",
    "expressjs":                "Express.js",
    "express.js":               "Express.js",
    "express js":               "Express.js",
    "html5":                    "HTML",
    "html":                     "HTML",
    "css3":                     "CSS",
    "css":                      "CSS",
    "sass":                     "CSS",
    "scss":                     "CSS",
    "tailwind":                 "Tailwind CSS",
    "tailwindcss":              "Tailwind CSS",
    "redux":                    "Redux",
    "redux toolkit":            "Redux",
    "zustand":                  "Zustand",
    "webpack":                  "Webpack",
    "vite":                     "Vite",

    # SSR / rendering modes — critical for Scandid JD
    "ssr":                      "SSR",
    "server side rendering":    "SSR",
    "server-side rendering":    "SSR",
    "serverside rendering":     "SSR",
    "csr":                      "CSR",
    "client side rendering":    "CSR",
    "ssg":                      "SSG",
    "static site generation":   "SSG",
    "spa":                      "SPA",
    "single page application":  "SPA",

    # APIs & auth
    "rest":                     "REST API",
    "restful":                  "REST API",
    "restful api":              "REST API",
    "rest api":                 "REST API",
    "api":                      "REST API",
    "apis":                     "REST API",
    "graphql":                  "GraphQL",
    "jwt":                      "JWT",
    "json web token":           "JWT",
    "oauth":                    "OAuth",
    "websocket":                "WebSockets",
    "websockets":               "WebSockets",
    "authentication":           "Authentication",
    "auth":                     "Authentication",
    "authorization":            "Authorization",

    # ── Python ────────────────────────────────────────────────────────────────
    "python3":                  "Python",
    "python":                   "Python",
    "py":                       "Python",
    "django":                   "Django",
    "flask":                    "Flask",
    "fastapi":                  "FastAPI",
    "pandas":                   "Pandas",
    "numpy":                    "NumPy",
    "sklearn":                  "Scikit-learn",
    "scikit learn":             "Scikit-learn",
    "scikit-learn":             "Scikit-learn",
    "scikit":                   "Scikit-learn",
    "pytorch":                  "PyTorch",
    "torch":                    "PyTorch",
    "tensorflow":               "TensorFlow",
    "tf":                       "TensorFlow",
    "keras":                    "Keras",
    "langchain":                "LangChain",
    "langgraph":                "LangGraph",
    "streamlit":                "Streamlit",
    "llama":                    "LLaMA",
    "llama2":                   "LLaMA2",
    "llama 2":                  "LLaMA2",
    "ollama":                   "Ollama",
    "openai":                   "OpenAI",
    "gpt":                      "GPT",
    "gpt4":                     "GPT-4",
    "gpt-4":                    "GPT-4",
    "huggingface":              "HuggingFace",
    "hugging face":             "HuggingFace",

    # ── Databases ─────────────────────────────────────────────────────────────
    "mongo":                    "MongoDB",
    "mongodb":                  "MongoDB",
    "postgres":                 "PostgreSQL",
    "postgresql":               "PostgreSQL",
    "mysql":                    "MySQL",
    "sqlite":                   "SQLite",
    "redis":                    "Redis",
    "elasticsearch":            "Elasticsearch",
    "dynamo":                   "DynamoDB",
    "dynamodb":                 "DynamoDB",
    "sql":                      "SQL",
    "nosql":                    "NoSQL",
    "orm":                      "ORM",
    "mongoose":                 "Mongoose",
    "prisma":                   "Prisma",

    # ── DevOps / Cloud ────────────────────────────────────────────────────────
    "docker":                   "Docker",
    "kubernetes":               "Kubernetes",
    "k8s":                      "Kubernetes",
    "aws":                      "AWS",
    "amazon web services":      "AWS",
    "gcp":                      "GCP",
    "google cloud":             "GCP",
    "azure":                    "Azure",
    "microsoft azure":          "Azure",
    "ci/cd":                    "CI/CD",
    "cicd":                     "CI/CD",
    "github actions":           "GitHub Actions",
    "jenkins":                  "Jenkins",
    "terraform":                "Terraform",
    "nginx":                    "Nginx",
    "linux":                    "Linux",
    "bash":                     "Bash",
    "devops":                   "DevOps",
    "dev ops":                  "DevOps",

    # ── General Dev Tools ─────────────────────────────────────────────────────
    "git":                      "Git",
    "github":                   "GitHub",
    "gitlab":                   "GitLab",
    "postman":                  "Postman",
    "vscode":                   "VS Code",
    "vs code":                  "VS Code",
    "jira":                     "Jira",
    "figma":                    "Figma",
    "agile":                    "Agile",
    "scrum":                    "Scrum",
    "tdd":                      "TDD",
    "test driven":              "TDD",
    "unit test":                "Unit Testing",
    "unit testing":             "Unit Testing",
    "integration test":         "Integration Testing",
    "jest":                     "Jest",
    "mocha":                    "Mocha",
    "cypress":                  "Cypress",

    # ── Languages ─────────────────────────────────────────────────────────────
    "java":                     "Java",
    "spring boot":              "Spring Boot",
    "springboot":               "Spring Boot",
    "c++":                      "C++",
    "cpp":                      "C++",
    "golang":                   "Go",
    "go lang":                  "Go",
    "rust":                     "Rust",
    "ruby":                     "Ruby",
    "rails":                    "Ruby on Rails",
    "php":                      "PHP",
    "swift":                    "Swift",
    "kotlin":                   "Kotlin",

    # ── Concepts ──────────────────────────────────────────────────────────────
    "ml":                       "Machine Learning",
    "machine learning":         "Machine Learning",
    "dl":                       "Deep Learning",
    "deep learning":            "Deep Learning",
    "nlp":                      "NLP",
    "natural language processing": "NLP",
    "cv":                       "Computer Vision",
    "computer vision":          "Computer Vision",
    "cnn":                      "CNN",
    "llm":                      "LLM",
    "large language model":     "LLM",
    "rag":                      "RAG",
    "retrieval augmented generation": "RAG",
    "ai":                       "AI",
    "artificial intelligence":  "AI",
    "microservices":            "Microservices",
    "micro services":           "Microservices",
    "fullstack":                "Full Stack",
    "full stack":               "Full Stack",
    "full-stack":               "Full Stack",
    "frontend":                 "Frontend",
    "front end":                "Frontend",
    "front-end":                "Frontend",
    "backend":                  "Backend",
    "back end":                 "Backend",
    "back-end":                 "Backend",
    "async":                    "Async",
    "asynchronous":             "Async",
    "concurrency":              "Concurrency",
    "caching":                  "Caching",
    "indexing":                 "Indexing",
    "hashing":                  "Hashing",
    "bcrypt":                   "bcrypt",
}


def normalize_skill(skill: str) -> str:
    """Normalize one skill string to its canonical form."""
    return SKILL_ALIASES.get(skill.lower().strip(), skill)


def normalize_skills(skill_set: set) -> set:
    """Normalize an entire set of skill strings."""
    return {normalize_skill(s) for s in skill_set}
